version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    container_name: php-gateway
    volumes:
      - .:/var/www/html
    ports:
      - '8080:8080'
      - '80:80'